* materm (read: my terminal)
  
  Ever pondered what would happen if you try to come up with your own terminal?
  Well, I did, and here's what happened !

** mashell
   
   It goes without saying what use is a terminal of without any shell? 
   Well, worry not, here's a shell for our very own terminal ;)

   No, this is not your usual shell, it does nothing what you're regular *nix shell does (in terms of 
   executing commands, but the concept of shell is same).

** Run

   If you dare running maTerm, do the following:

   #+begin_src sh
     make
   #+end_src

   This will compile and make executable(s). And then :

   #+begin_src shell
     ./materm
   #+end_src

   Voila, you should see an ugly black screen right away :P 
  
** Dependencies 
   
   Require:
   - libgtk-+3.0
   - libvte-2.91
** Features
   
   To be added !! :P :D
** TODOs

*** Add color support to materm
    make text green, to get the real deal hacker vibe ;)

*** Maybe add some useful functions?
    dont have anything in mind, yet.
  
*** Text Editor ?
    If I'm brave enough. :-\
